"""
reflection_controller
=====================

Controller for removing reflections from a batch of crate images
given precomputed masks.  This module reads each original image
along with its mask, applies inpainting via the
:class:`app.model.reflection_removal_model.ReflectionRemovalModel`,
and writes the cleaned image to disk.  It can be invoked from
``main_Reflection_Removal.py`` or directly via
``python -m app.controller.reflection_controller``.

The default input directory for images is ``data/images`` and the
default mask directory is ``mask``.  Results are saved in
``result``.
"""

from __future__ import annotations

from pathlib import Path
import sys
import cv2

from app.model.reflection_removal_model import ReflectionRemovalModel


def process_images(images_dir: Path, mask_dir: Path, result_dir: Path) -> None:
    """Remove reflections from all images in ``images_dir`` using masks in ``mask_dir``.

    Parameters
    ----------
    images_dir : pathlib.Path
        Directory containing the original images (BGR format).
    mask_dir : pathlib.Path
        Directory containing corresponding binary masks generated by
        the mask controller.  Each mask must be named
        ``<stem>_mask.png`` for an image named ``<stem>.<ext>``.
    result_dir : pathlib.Path
        Directory where the reflection–removed images will be saved.
        Created automatically if it does not exist.
    """
    if not images_dir.is_dir():
        raise NotADirectoryError(f"Images directory not found: {images_dir}")
    if not mask_dir.is_dir():
        raise NotADirectoryError(f"Mask directory not found: {mask_dir}")
    result_dir.mkdir(parents=True, exist_ok=True)
    rr_model = ReflectionRemovalModel()
    for img_path in sorted(images_dir.iterdir()):
        if img_path.suffix.lower() not in {".png", ".jpg", ".jpeg", ".bmp", ".tif", ".tiff"}:
            continue
        stem = img_path.stem
        mask_path = mask_dir / f"{stem}_mask.png"
        if not mask_path.exists():
            print(f"Warning: mask not found for {img_path.name}, skipping.", file=sys.stderr)
            continue
        img = cv2.imread(str(img_path), cv2.IMREAD_COLOR)
        mask = cv2.imread(str(mask_path), cv2.IMREAD_GRAYSCALE)
        if img is None or mask is None:
            print(f"Warning: failed to load image or mask for {img_path.name}, skipping.", file=sys.stderr)
            continue
        result = rr_model.remove_reflections(img, mask)
        out_path = result_dir / f"{stem}_reflection_removed.png"
        cv2.imwrite(str(out_path), result)
        print(f"Reflection removed image saved: {out_path}")


def main() -> None:
    """Entry point for command–line execution.

    Removes reflections from all images in the default ``data/images``
    directory and writes results to ``result``.
    """
    images_dir = Path("data/images")
    mask_dir = Path("mask")
    result_dir = Path("result")
    process_images(images_dir, mask_dir, result_dir)


if __name__ == "__main__":
    main()