paths:
  input_dir: "data/images"
  out_mask: "out/mask"
  out_result: "out/result"
  out_eval: "out/eval"
  out_logs: "out/logs"

container:
  a_threshold: 126
  erode_iter: 1

detect:
  z_sigma: 11
  z_thresh: 2.0
  sat_cut: 245
  s_thresh: 40
  rgb_range_thresh: 25
  min_area: 20

shape:
  thin_min_short: 8
  thin_aspect_min: 4.0
  thin_area_max: 400
  dilate_thin: 1
  dilate_blob: 2

inpaint:
  radius: 3
  feather: 2

eval:
  epr_band: 3

debug:
  save_panels: true
